spring:
    redis:
        database: 0
        host: 192.168.0.58
        password: ''
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 0.0
