server:
    port: 1234
#    context-path: #/liuzh/


spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:oracle:thin:@47.92.67.90:1521:orcl
      username: sdtd27
      password: sdtd27
      driver-class-name: oracle.jdbc.driver.OracleDriver
      minIdle: 10
      maxActive: 200
      initialSize: 5
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 3000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMill
logging:
  config: classpath:logback-spring.xml
#url加密  用于swagger模块
security:
  basic:
    path: /swagger-ui.html
    enabled: true
  user:
    name: sdtd27
    password: sdtd27

#      mysql:
#        type: com.alibaba.druid.pool.DruidDataSource
#        url: jdbc:mysql://192.168.1.246:3306/repair?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
#        username: root
#        password: 123456
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        validationQuery: SELECT 1
#        testWhileIdle: true

#    aop:
#      auto: true