server:
    port: 8098
    context-path: /userCenter/
token:
  expiretime: 300000000
spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:oracle:thin:@47.94.131.120:1521:orcl
#      url: jdbc:oracle:thin:@192.168.1.111:1521:LIUZE
      username: sdtd27
      password: sdtd27
      driver-class-name: oracle.jdbc.OracleDriver
      minIdle: 10
      maxActive: 200
      initialSize: 5
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 3000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMill
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
    application:
      name: userCenter
    redis:
        database: 0
        host: 39.106.206.129
        port: 6379
        password: Rzt82890758-Rzt82890758
        timeout: 0
        pool:
          max-active: 100
          max-idle: 8
          min-idle: 0
          max-wait: -1
eureka:
  client:
    service-url:
      defaultZone: http://39.106.206.129:7002/eureka/
logging:
  config: classpath:logback-spring.xml