server:
    port: 8098
    context-path: /userCenter
token:
  expiretime: 300000000
spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://168.130.1.31:30624/sdtd27?useUnicode=true&characterEncoding=utf8
#      url: jdbc:oracle:thin:@192.168.1.111:1521:LIUZE
      username: sdtd27
      password: sdtd27
      driver-class-name: com.mysql.jdbc.Driver
      minIdle: 10
      maxActive: 200
      initialSize: 5
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 3000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMill
    jpa:
      database: ORACLE
      hibernate:
        ddl-auto: none
      show-sql: true
    application:
      name: userCenter
    redis:
        database: 0
        host: 168.130.1.31
        port: 31662
        password:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
        timeout: 0
eureka:
  client:
    service-url:
      defaultZone: http://168.130.1.31:31814/eureka/
logging:
  config: classpath:logback-spring.xml