server:
  port: 7011
  context-path: /nurseTask/
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://168.130.1.31:30624/sdtd27?useUnicode=true&characterEncoding=utf8
    username: sdtd27
    password: sdtd27
    driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: oracle.jdbc.driver.OracleDriver
    initialSize: 5
    minIdle: 5
    maxActive : 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
     show-sql: true
     database: ORACLE
  application:
    name: nurseTask
eureka:
  client:
    service-url:
      defaultZone: http://168.130.1.30:31814/eureka
#spring:
#  profiles:
#    active: prd
#
#    #


#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://168.130.7.10:3306/sdtd2
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    database: mysql
#    show-sql: true
