server:
  port: 7011
  context-path: /nurseTask/
#log
logging:
  config: classpath:logback.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@168.130.1.32:1521:orcl
   # url: jdbc:oracle:thin:@47.94.131.120:1521:sdt
   # url: jdbc:mysql://168.130.1.31:30624/sdtd27?useUnicode=true&characterEncoding=utf8
    #username: sdtd
    #password: sdtd
    username: sdtd27
    password: sdtd27
    driver-class-name: oracle.jdbc.driver.OracleDriver
    initialSize: 5
    minIdle: 5
    maxActive : 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
     show-sql: true
     database: ORACLE
 #    hibernate:
  #     ddl-aut
  application:
    name: nurseTask
#  redis:
#      database: 0
#      host: 39.106.206.129
#      port: 6379
#      password: Rzt82890758-Rzt82890758
#      timeout: 0
  redis:
        database: 0
        host: 168.130.1.31
        port: 31662
        password:
        timeout: 0
        pool:
          max-active: 100
          max-idle: 8
          min-idle: 0
          max-wait: -1
eureka:
  client:
    service-url:
    #  defaultZone: http://168.130.1.31:7003/eureka/
    #  defaultZone: http://168.130.1.31:7003/eureka/
     #  defaultZone: http://192.168.21.31:7002/eureka/
      defaultZone: http://192.168.21.25:7002/eureka/
  instance:
    prefer-ip-address: true
#spring:
#  profiles:
#    active: prd
#
#    #


#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://168.130.7.10:3306/sdtd2
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    database: mysql
#    show-sql: true
