server:
  port: 8097
spring:
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://168.130.1.31:31814/eureka/
zuul:
  routes:
    userCenter:
      path: /userCenter/**
      serviceId: http://168.130.1.31:32332
      stripPrefix: false
    xsTask:
      path: /xsTask/**
      serviceId: http://168.130.1.31:32165
      stripPrefix: false
    nurseTask:
      path: /nurseTask/**
      serviceId: http://168.130.1.31:32021
      stripPrefix: false
    linedata:
      path: /linedata/**
      serviceId: http://168.130.1.31:32727
      stripPrefix: false
    fileServer:
      path: /fileserver/**
      url: http://168.130.1.31:31235
      stripPrefix: false
    imgUrl:
      path: /img/**
      url: http://168.130.1.31:31141
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false