server:
  port: 8097
spring:
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
       defaultZone: http://168.130.1.31:31814/eureka/
zuul:
  routes:
    userCenter:
      path: /userCenter/**
      serviceId: http://168.130.1.31:32332
      stripPrefix: false
      ribbon:
        ReadTimeout: 60000
        ConnectTimeout: 60000
    xsTask:
      path: /xsTask/**
      serviceId: http://168.130.1.31:32165
      stripPrefix: false
      ribbon:
        ReadTimeout: 60000
        ConnectTimeout: 60000
    nurseTask:
      path: /nurseTask/**
      serviceId: http://168.130.1.31:32021
      stripPrefix: false
      ribbon:
        ReadTimeout: 60000
        ConnectTimeout: 60000
    linedata:
      path: /linedata/**
      serviceId: http://168.130.1.31:32727
      stripPrefix: false
      ribbon:
        ReadTimeout: 60000
        ConnectTimeout: 60000
    fileServer:
      path: /fileserver/**
      url: http://168.130.1.31:31235
      stripPrefix: false
      ribbon:
        ReadTimeout: 60000
        ConnectTimeout: 60000
    imgUrl:
      path: /img/**
      url: http://168.130.1.31:31141
  host:
    connect-timeout-millis: 60000




