server:
  port: 8097
spring:
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.111:7002/eureka/
zuul:
  routes:
    userCenter:
      path: /userCenter/**
      serviceId: userCenter
